// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihixxakshuodzobzkoxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaXh4YWtzaHVvZHpvYnprb3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTcwNTQsImV4cCI6MjA1ODU5MzA1NH0.yrGEuwS3JgKdnLbbpJbmBcZoEc43Iel-jcEuDNzTsT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);